P/urls.py
from django.contrib import admin
from django.urls import path,include
import app
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app.urls")),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path,re_path
from . import views
app_name="app"

urlpatterns = [
    path('',views.index,name="index"),
    path('radio/',views.radio,name="radio"),
    path('checkbox/',views.checkbox,name="checkbox"),
    path('select/',views.select,name="select"),
    path('radioop/',views.radio_output,name="radioop"),
    path('file/',views.file_demo,name="file_demo"),
    path('create_topic/',views.create_topic,name="create_topic"),
    path('create_webpage/',views.create_webpage,name="create_webpage"),
    path('select_topic/',views.select_topic,name="select_topic"),
    path('topic_select/',views.topic_select,name="topic_select"),
    path('disp_web/',views.disp_web,name="disp_web"),
]

app/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    topic=models.CharField(max_length=50,primary_key=True)

    def __str__(self):
        return self.topic

class Webpage(models.Model):
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    name=models.CharField(max_length=100,primary_key=True)
    url=models.URLField(unique=True)

    def __str__(self):
        return self.name

class Access_Details(models.Model):
    web_name=models.ForeignKey(Webpage,on_delete=models.CASCADE)
    date=models.DateField()

    def __str__(self):
        return str(self.web_name)
    
    
    

app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from app.models import *
import populate
from django.db.models import Q
# Create your views here.
def index(request):
    if request.method=="POST":
        return render(request,"form_demo.html",context={'value':request.POST.get("username")})
        
    return render(request,"form_demo.html")

def radio(request):
    return render(request,"radio.html")

def checkbox(request):
    if request.method=="POST" :
        print(request.POST.getlist("gender"))
        return HttpResponse("selected gender is \"{}\"".format(request.POST.getlist("gender")))
    return render(request,"checkbox.html")

def select(request):
    if request.method=="POST":
        return HttpResponse("selected country is \"{}\"".format(request.POST.getlist("country")))
    return render(request,"select.html")

def radio_output(request):
    print("Control in radio output")
    return HttpResponse("selected gender is \"{}\"".format(request.GET.get("gender")))

import os
def file_demo(request):
    img_url=None
    if request.method=="POST" and request.FILES['profile']:
        profile_pic=request.FILES['profile']
        fs=FileSystemStorage(location=os.path.join(settings.MEDIA_DIR,"images"))
        file_name=fs.save(profile_pic.name,profile_pic)
        img_url=fs.url(file_name)
                
    return render(request,"file_demo.html",context={'img_url':img_url})

def create_topic(request):
    if request.method=="POST":
        populate.add_topic(topic=request.POST['topic'])
        return HttpResponse("<h1> Topic Added Successfully </h1>")
    return render(request,'create_topic.html')

def create_webpage(request):
    if request.method=="POST":
        populate.add_webpage(request.POST['topic'],\
            request.POST['name'],request.POST['url'])
        return HttpResponse("<h1>webpage created successfully</h1>")
    topics=Topic.objects.all()
    return render(request,"create_webpage.html",\
        context={'topics':topics})    

def select_topic(request):
    d={'topics':Topic.objects.all()}
    if request.method=="POST":
        topic=request.POST['topic']
        #topic_obj=Topic.objects.get(topic=topic)
        #topic_obj=Topic.objects.get(topic__icontains=topic)
        topic_obj=Topic.objects.get(topic__istartswith=topic)
        return HttpResponse("<h1>{}</h1>".format(topic_obj.topic))
    return render(request,"select_topic.html",context=d)

def topic_select(request):
    d={'topics':Topic.objects.all()}
    return render(request,"topic_select.html",context=d)

def disp_web(request):
    topic_name=request.GET['topic']
    topic=Topic.objects.get(topic__icontains=topic_name)
    #d={"webpages":Webpage.objects.filter(~Q(topic=topic))}
    d={"webpages":Webpage.objects.exclude(topic=topic)}
    return render(request,"disp_web.html",d)

templates/checkbox.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form Demo2</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <input type="checkbox" name="gender" id="gender" value="Male"> Male <br>
        <input type="checkbox" name="gender" id="gender" value="Female"> Female <br>
        
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/create_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Topics Form</title>
</head>
<body>
    <h1>Create Topic</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="topic">Topic Name </label>
        <input type="text" name="topic" id="topic"><br>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/create_webpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Topics Form</title>
</head>
<body>
    <h1>Create Webpage</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="topic">Topic</label>
        <select name="topic" id="topic">
            {% for topic in topics %}
            <option value={{topic}}>{{topic}}</option>          
            {% endfor %}
        </select><br>
            <label for="name">Webpage Name </label>
            <input type="text" name="name" id="name"><br>
            <label for="url">Webpage url </label>
            <input type="url" name="url" id="url"><br>
    
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/disp_web.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Webpage Details</title>
</head>
<body>
    {% if webpages %}
      <table border="2pt">
          <tr>
              <th>Topic Name</th>
              <th>Webpage Name</th>
              <th>Webpage URL</th>
          </tr>
          {% for webpage in webpages %}
          <tr>
              <td>{{webpage.topic.topic}}</td>
              <td>{{webpage.name}}</td>
              <td>{{webpage.url}}</td>
          </tr>
            
          {% endfor %}
      </table>
    {% else %}
      <h1>No Data Found</h1>
    {% endif %}
    
</body>
</html>

templates/file_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>file upload</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="img">Profile Pic</label>
        <input type="file" name="profile" id="img">
        <input type="submit" value="Submit">
    </form>
    {% if img_url %}
    <h1>{{img_url}}</h1>
    <img src="{{img_url}}" alt="no image" height="100" width="80">
      
    {% endif %}
</body>
</html>

templates/form_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HTML FORM DEMO</title>
</head>
<body>
    <h1>Fille the below form</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="username">UserName</label>
        {% if value %}
        <input type="text" name="username" id="username" value={{value}}>
        {% else %}
        <input type="text" name="username" id="username"> 
        {% endif %}
        
        
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/radio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form Demo2</title>
</head>
<body>
    <!-- <form action="{% url 'app:radioop' %}" method="GET"> -->
    <form action="/radioop/" method="GET">
        {% csrf_token %}
        <input type="radio" name="gender" id="gender" value="Male"> Male <br>
        <input type="radio" name="gender" id="gender" value="Female"> Female <br>
        
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/select.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form Demo2</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <label for="cont">country</label>
        <select name="country" id="cont" multiple>
            <option value="India">India</option>
            <option value="USA"> USA </option>
            <option value="UK">UK</option>
        </select>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/select_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Topic</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
            {% if topics %}
            <label for="topic">Topic</label>
            <select name="topic" id="topic">
            {% for topic in topics %}
            <option value={{topic.topic}}>{{topic.topic}}</option>
            {% endfor %}
            </select>
            {% else %}
              <h1>No Data Found</h1>
            {% endif %}
            <input type="submit" value="Submit">
        
    </form>
</body>
</html>

templates/topic_select.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Topic</title>
</head>
<body>
    <form action="{% url 'app:disp_web' %}" method="GET">
            {% if topics %}
            <label for="topic">Topic</label>
            <select name="topic" id="topic">
            {% for topic in topics %}
            <option value={{topic.topic}}>{{topic.topic}}</option>
            {% endfor %}
            </select>
            {% else %}
              <h1>No Data Found</h1>
            {% endif %}
            <input type="submit" value="Submit">
        
    </form>
</body>
</html>